export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_POSTS_INIT = 'FETCH_POSTS_INIT';
export const SET_POST_AS_CURRENT = 'SET_POST_AS_CURRENT';